### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sparklytopaz** [awslabs/dgl-lifesci#101]
for python find_reaction_center_train.py --train-path x --val-path y 
![image](https://user-images.githubusercontent.com/31735343/95067685-ce37a300-0721-11eb-9ec6-891d2169d4da.png)

could not reopen the closed issue as the issue wasn't started by me
this error is still persisting and i created a new environment just to train on my own dataset

**Comment by mufeili** [comment]
0.2.5 is not enough as the fix is performed after 0.2.5. You need to git clone the repo and install from source.

**Comment by sparklytopaz** [comment]
git clone https://github.com/awslabs/dgl-lifesci.git
cd dgl-lifesci/python
python setup.py install

I used this
Yes they are the same I used previously

**Comment by sparklytopaz** [comment]
The issue was with the text input file
