### ISSUE TITLE
rexgen_direct notebook error

### ISSUE THREAD

**Issue by eacwecwecd** [awslabs/dgl-lifesci#108]
when I run https://data.dgl.ai/dgllife/reaction_prediction_pretrained.ipynb, I got this error:
      IndexError: tensors used as indices must be long, byte or bool tensors

the error from this line,

with torch.no_grad():
    _, biased_pred = reaction_center_prediction(str(device), center_model, batch_mol_graphs, batch_complete_graphs)

**Comment by mufeili** [comment]
What's your PyTorch version?

**Comment by eacwecwecd** [comment]
> What's your PyTorch version?
1.6

**Comment by mufeili** [comment]
What are the versions for DGL and DGL-LifeSci?

**Comment by eacwecwecd** [comment]
> What are the versions for DGL and DGL-LifeSci?

DGL is 0.5.2, DGL-LifeSci is 0.2.5

**Comment by mufeili** [comment]
Can you update to DGL-LifeSci 0.2.6? I just tried myself and the issue happens with 0.2.5, but not with 0.2.6.

**Comment by eacwecwecd** [comment]
> Can you update to DGL-LifeSci 0.2.6? I just tried myself and the issue happens with 0.2.5, but not with 0.2.6.
So many thanks for your quick help！
