### ISSUE TITLE
Why does GCNLayer have norm="none"?

### ISSUE THREAD

**Issue by haozhu233** [awslabs/dgl-lifesci#113]
Hello, thanks for this package! One quick question: why do we have `norm="none"` in `GCNLayer`? I think the default is `both` as described in the paper. 

https://github.com/awslabs/dgl-lifesci/blob/c6fe2f20c68d75721061483db755185de9fdbedc/python/dgllife/model/gnn/gcn.py#L43-L44

**Comment by mufeili** [comment]
There are two reasons:
- [Inductive Representation Learning on Large Graphs](https://arxiv.org/abs/1706.02216) suggests that the symmetric adjacency normalization may not work well in the setting of multiple graphs as they can have different degree distributions.
- [How Powerful Are Graph Neural Networks?](https://arxiv.org/abs/1810.00826) suggests that `norm="none"` can be better than `norm="right"` as to distinguish two graphs the numbers of node degrees also matter.

**Comment by haozhu233** [comment]
@mufeili Thanks for the explanation! That makes sense. It might be a good idea to make it a function parameter though. People will notice this deviation from default more easily without going through the code.
