### ISSUE TITLE
dgllife.utils.early_stop write out epoch in checkpoint

### ISSUE THREAD

**Issue by andt88** [awslabs/dgl-lifesci#132]
After running a hyperparameter search using early stopping with hold-out validation, I would like to retrain the model on the training+validation datasets. For this I require the epoch of the Early Stopping checkpoint. To my knowledge, this is currently not being saved.

**Comment by mufeili** [comment]
Are you using the scripts [here](https://github.com/awslabs/dgl-lifesci/tree/master/examples/property_prediction/csv_data_configuration)?

**Comment by andt88** [comment]
Yes.
