### ISSUE TITLE
Dataset download is not working with multiple jobs and load set to true

### ISSUE THREAD

**Issue by VIGNESHinZONE** [awslabs/dgl-lifesci#136]
# Dataset downloads have gotten very slow and are not working when multiple jobs are given.

Im running all my experiments on collab and can be reproduced [here](https://colab.research.google.com/drive/1CFYUXOEfXbQax4A3KptVQPGES_PKe725?usp=sharing) ( Code in the 4th block. Sorry for the long code but Im implementing a paper for contribution.)

### It was working perfectly a few days ago and I was getting the following results (You can clearly see that it gets downloaded in 1min)- 
![Screenshot from 2021-02-18 03-01-02](https://user-images.githubusercontent.com/45672459/108276986-a7dd4600-719e-11eb-83ea-b7dbb18a923b.jpg)

### This was today (It wasn't downloading until I removed the load and n_jobs parameters )- 
This code has been running for 10mins, and still no results
![Screenshot from 2021-02-18 03-09-33](https://user-images.githubusercontent.com/45672459/108277165-fd195780-719e-11eb-868a-81248d50deeb.jpg)

**Comment by mufeili** [comment]
It seems like the issue is not about downloading, but multiprocessing. You probably have launched too many processes that get stuck, can you try setting `n_jobs` to 1?

**Comment by VIGNESHinZONE** [comment]
Yes, got it working. I was probably running too many processes. Thanks
