### ISSUE TITLE
Scaffold splitter functionality unexpected behavior?

### ISSUE THREAD

**Issue by phil-fradkin** [awslabs/dgl-lifesci#144]
Hello dear authors,

I wanted to confirm my understanding of the scaffold functionality. When using the default initialization I noticed that the indices returned are continuous which I find suspicious since the documentation mentions: 
```
Group molecules so that all molecules in a group have a same scaffold (see reference).
The dataset is then split at the level of groups.
```

To reproduce:
```
dataset = dgllife.data.Tox21(smiles_to_bigraph, CanonicalAtomFeaturizer())
split = ScaffoldSplitter()
train, test, val = split.train_val_test_split(dataset)
np.max(train.indices), np.min(train.indices), np.max(test.indices), np.min(test.indices), np.max(val.indices), np.min(val.indices)
```
Note that this does not happen when using the smiles `scaffold_func`. 

### Reason for occurrence 

https://github.com/awslabs/dgl-lifesci/blob/2fbf5fd6aca92675b709b6f1c3bc3c6ad5434e96/python/dgllife/utils/splitters.py#L494
I think this occurs because the object returned by `AllChem.MurckoDecompose` seems to always be unique (which I would not expect given the description of the function) 
```
In [56]: AllChem.MurckoDecompose(mol)
Out[56]: <rdkit.Chem.rdchem.Mol at 0x7fc076dbe530>

In [57]: AllChem.MurckoDecompose(mol)
Out[57]: <rdkit.Chem.rdchem.Mol at 0x7fc076d198a0>

In [58]: obj1 = AllChem.MurckoDecompose(mol)

In [59]: obj2 = AllChem.MurckoDecompose(mol)

In [60]: obj1 == obj2
Out[60]: False
```

Thus when using the returned object as a key for the dictionary the key will always be unique. 
```
scaffolds = defaultdict(list)

for i, mol in enumerate(molecules):
    # For mols that have not been sanitized, we need to compute their ring information
    
    FastFindRings(mol)
    if scaffold_func == 'decompose':
        mol_scaffold = AllChem.MurckoDecompose(mol)
    if scaffold_func == 'smiles':
        mol_scaffold = MurckoScaffold.MurckoScaffoldSmiles(
                mol=mol, includeChirality=False)
        # Group molecules that have the same scaffold
    scaffolds[mol_scaffold].append(i)
```
```
In [54]: all([len(x[1]) == 1 for x in scaffolds.items()] )
Out[54]: True
```

### Smiles scaffold func
When I run a similar experiment with the smiles scaffold function the output as expected has multiple molecules belonging to a single scaffold
```
In [67]: pd.value_counts([len(x[1]) for x in scaffolds.items()])
Out[67]:
1       1773
2        261
3        112
4         48
5         32
6         19
7         11
11        10
8          8
12         5
9          5
10         4
13         4
14         3
```

I hope that this isn't a wild goose chase and will prove to be a useful investigation in improving functionality of this great library. Many thanks
-Phil

**Comment by mufeili** [comment]
Great catch! I confirmed the issue with `Tox21` and `PCBA`. The latter one is much larger, with 437929 molecules. It turns out that we need to use `Chem.MolToSmiles(AllChem.MurckoDecompose(mol))` instead. With that I now see

```ipython
In [1]: pd.value_counts([len(x[1]) for x in scaffolds.items()])
Out[1]:
1       1872
2        256
3         98
4         50
5         29
6         21
11        10
7         10
8          9
12         5
9          5
13         3
10         3
17         3
26         3
20         2
18         2
14         2
24         2
15         2
29         2
35         2
16         1
69         1
83         1
38         1
40         1
48         1
1474       1
63         1
89         1
21         1
23         1
27         1
45         1
1781       1
dtype: int64
```

**Comment by phil-fradkin** [comment]
Glad it was an easy fix!
