### ISSUE TITLE
Utils that do not use RDKit

### ISSUE THREAD

**Issue by jadolfbr** [awslabs/dgl-lifesci#148]
Some utils do not use RDKit - but it seems as though the requirement is there anyway. 
Many of us deal with proteins and not small molecules -  and on large clusters, RDKit installation can be a pain. 

Is there any way to have utils be case-by-case for RDKit?.   Two that are well used and independent are:
- Meter
- EarlyStopping

These clearly do not need RDKit, but it needs to be installed anyway.

**Comment by mufeili** [comment]
This should be addressed in #147 . You can try installing from the source and see if you can now use utils like `Meter` and `EarlyStopping` without RDKit.
