### ISSUE TITLE
MGCN Edge embedding 

### ISSUE THREAD

**Issue by NicoRenaud** [awslabs/dgl-lifesci#151]
Hi,

I was looking at `mgc.py` and I'm wondering if in `get_edge_types` of `EdgeEmbedding` it should be : 

```python
(torch.abs(node_type1 - node_type2) - 1) ** 2 // 4
```

instead of 

```python
(torch.abs(node_type1 - node_type2) - 1) ** 2 / 4
```
otherwise the edge types are not integer and torch doesn't really like that. 

Thanks for all the work you've done on the library !

**Comment by mufeili** [comment]
Thanks for the report. This has been fixed.
