### ISSUE TITLE
load_pretrained 

### ISSUE THREAD

**Issue by ph-mehdi** [awslabs/dgl-lifesci#155]
I want to change the model selected as a pretrain, for example GCN_attentivefp_SIDER, the last layer and change the output to 100 instead of 27.
And also how can I access the implementations of this models?

**Comment by ph-mehdi** [comment]
Thank you for your answer.
For tox21, I can easily get the vector without changing the last layer, but I do the same for sider, I get an error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-10dbdc816a92> in <module>()
----> 1 label_pred = model_sider(g, feats)
      2 print(smiles)                   
      3 print(label_+pred[:, mask_s != 0])

9 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in _verify_batch_size(size)
   2245         size_prods *= size[i + 2]
   2246     if size_prods == 1:
-> 2247         raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
   2248 
   2249 

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

**Comment by mufeili** [comment]
`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])`

This is probably due to the use of something like batch normalization, which requires a batch size bigger than 1 during training. Typically if you use a batch size `B` greater than 1 during training, the last batch can have a batch size smaller than `B`, which can be 1 in your case. You can simply drop the last batch during training.

**Comment by ph-mehdi** [comment]
@mufeili Thank you for your answer
I'm adding GCN_attentivefp_SIDER.
But I want to give the sider set to it, I get the following error.

<ipython-input-14-443433044f05> in <module>()
      2 smiles, g, label, mask = dataset[0]
      3 feats = g.ndata.pop('h')
----> 4 label_pred = model(g, feats)
      5 print(smiles)                   # CCOc1ccc2nc(S(N)(=O)=O)sc2c1
      6 print(label_pred[:, mask != 0])

7 frames
/usr/local/lib/python3.7/dist-packages/dgl/nn/pytorch/conv/graphconv.py in forward(self, graph, feat, weight, edge_weight)
    424                 rst = graph.dstdata['h']
    425                 if weight is not None:
--> 426                     rst = th.matmul(rst, weight)
    427 
    428             if self._norm != 'none':

RuntimeError: mat1 and mat2 shapes cannot be multiplied (13x74 and 39x256)

**Comment by mufeili** [comment]
> @mufeili Thank you for your answer I'm adding GCN_attentivefp_SIDER. But I want to give the sider set to it, I get the following error.
> 
> in () 2 smiles, g, label, mask = dataset[0] 3 feats = g.ndata.pop('h') ----> 4 label_pred = model(g, feats) 5 print(smiles) # CCOc1ccc2nc(S(N)(=O)=O)sc2c1 6 print(label_pred[:, mask != 0])
> 
> 7 frames /usr/local/lib/python3.7/dist-packages/dgl/nn/pytorch/conv/graphconv.py in forward(self, graph, feat, weight, edge_weight) 424 rst = graph.dstdata['h'] 425 if weight is not None: --> 426 rst = th.matmul(rst, weight) 427 428 if self._norm != 'none':
> 
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (13x74 and 39x256)

Can you provide your DGL version, DGL-LifeSci version and a runnable script to reproduce the issue you encountered?

**Comment by ph-mehdi** [comment]
DGL  version = 0.6.1
DGL-LifeSci = 0.2.8
surce code:

`from dgllife.data import SIDER `
`from dgllife.data import SIDER `
`from dgllife.model import load_pretrained`
`from dgllife.utils import smiles_to_bigraph, CanonicalAtomFeaturizer`

`dataset = SIDER(smiles_to_bigraph, CanonicalAtomFeaturizer())`
`model = load_pretrained('GCN_attentivefp_SIDER') # Pretrained model loaded`
`model.eval()`

`smiles, g, label, mask = dataset[2]`
`feats = g.ndata.pop('h')`
`label_pred = model(g, feats)`
`print(smiles) `             
`print(label_pred)`

I think the problem is with the input of the "GCN_attentivefp_SIDER" model. Because the shape is a variable feat, it is `torch.Size ([23, 74])`

**Comment by mufeili** [comment]
You need to use different featurizers for AttentiveFP:
```python
from dgllife.utils import smiles_to_bigraph, AttentiveFPAtomFeaturizer

dataset = SIDER(smiles_to_bigraph, AttentiveFPAtomFeaturizer())
```

**Comment by ph-mehdi** [comment]
Thanks, it worked
