### ISSUE TITLE
error g.ndata.pop ('h')

### ISSUE THREAD

**Issue by ph-mehdi** [awslabs/dgl-lifesci#156]
Hi
I do not understand why this command ` g.ndata.pop ('h')` gives the following error when it wants to run again.

KeyError                                  Traceback (most recent call last)
<ipython-input-13-e62c94d94b65> in <module>()
      5 for epoch in range(num_epochs):
      6     for i, (smiles, g, label, mask) in enumerate(sider_train):
----> 7         inputs = g.ndata.pop('h')
      8         inputs = inputs.to(device)
      9         targets = label.to(device)

2 frames
/usr/lib/python3.7/_collections_abc.py in pop(self, key, default)
    793         '''
    794         try:
--> 795             value = self[key]
    796         except KeyError:
    797             if default is self.__marker:

/usr/local/lib/python3.7/dist-packages/dgl/view.py in __getitem__(self, key)
     64             return ret
     65         else:
---> 66             return self._graph._get_n_repr(self._ntid, self._nodes)[key]
     67 
     68     def __setitem__(self, key, val):

/usr/local/lib/python3.7/dist-packages/dgl/frame.py in __getitem__(self, name)
    391             Column data.
    392         """
--> 393         return self._columns[name].data
    394 
    395     def __setitem__(self, name, data):

KeyError: 'h'

**Comment by mufeili** [comment]
This is similar to removing a key-value pair with key 'h' from a dictionary. After you call it once, the pair is removed and you will get an error if you call it the second time.

**Comment by ph-mehdi** [comment]
Thanks for the reply
I think then we have to build the dataset from scratch.
