### ISSUE TITLE
Pretrained models' in_feat dimension error

### ISSUE THREAD

**Issue by Jingyu-Peng** [awslabs/dgl-lifesci#162]
When I try to make predictions on ESOL dataset with pertained models:`'Weave_canonical_ESOL','Weave_attentivefp_ESOL','MPNN_canonical_ESOL','MPNN_attentivefp_ESOL'`, the feat_size of CanonicalBondFeaturizer and AttentiveFPBondFeaturizer are 12 and 10, but the pretrained models' in_feats are 13 and 11.

**Comment by mufeili** [comment]
Did you specify `self_loop=True` in initializing `CanonicalBondFeaturizer` and `AttentiveFPBondFeaturizer`? This will use an additional binary feature to indicate the self loops.

**Comment by Jingyu-Peng** [comment]
Yes, when I use `dataset_c = ESOL(smiles_to_bigraph, CanonicalAtomFeaturizer(),CanonicalBondFeaturizer(bond_data_field='h',self_loop=True))`, I get this error:`dgl._ffi.base.DGLError: Expect number of features to match number of edges. Got 100 and 68 instead.`

**Comment by mufeili** [comment]
Try

```python
from functools import partial

dataset_c = ESOL(partial(smiles_to_bigraph, add_self_loop=True), CanonicalAtomFeaturizer(),CanonicalBondFeaturizer(bond_data_field='h',self_loop=True))
```

The design here is not very nice and I'm sorry for the inconvenience.

**Comment by Jingyu-Peng** [comment]
That works! Thanks a lot!
