### ISSUE TITLE
mask error for MoleculeCSVDataset

### ISSUE THREAD

**Issue by nbrosse** [awslabs/dgl-lifesci#184]
MoleculeCSVDataset fails if load=True because the mask attribute is not set to None,

In https://github.com/awslabs/dgl-lifesci/blob/f854adf6f41ec5825f76783fb64c2b59ab520ef5/python/dgllife/data/csv_dataset.py#L131, we should add 
else
self.mask = None

```
  File "/usr/local/lib/python3.8/dist-packages/dgllife/data/csv_dataset.py", line 199, in __getitem__
    if self.mask is not None:
AttributeError: 'MoleculeCSVDataset' object has no attribute 'mask'
```

**Comment by mufeili** [comment]
Thanks for reporting the issue. Could you help open a PR to fix this?

**Comment by nbrosse** [comment]
Yep, sorry for the late reply,
Unfortunately I am not able to `python setup.py install` the project
I have the following error:
```
Cython.Compiler.Errors.CompileError: pandas/_libs/groupby.pyx
❯ pip show cython
Name: Cython
Version: 0.29.31
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: http://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /Users/nbrosse/.pyenv/versions/miniconda3-4.3.30/envs/dgllife/lib/python3.7/site-packages
Requires:
Required-by:
```

**Comment by mufeili** [comment]
No worries. I guess you need to fix your cython and/or related dependencies. Could you take a look at PR #189 and see if you are good with it?

**Comment by nbrosse** [comment]
Ok for me thanks ! :)
