### ISSUE TITLE
Question about pretraining dataset

### ISSUE THREAD

**Issue by kexinhuang12345** [awslabs/dgl-lifesci#188]
Hi! Thanks for this great package. 

I am wondering for the "gin_supervised_contextpred" and "gin_supervised_masking" pre-trained models, are they pre-trained first on the ChEMBL dataset in a supervised manner? If so, where can we find the list of bioassays that is used to pre-train? Thank you!

**Comment by mufeili** [comment]
Hi Kexin,

The ChEMBL dataset can be accessed by downloading "chem data" [here](https://github.com/snap-stanford/pretrain-gnns#dataset-download). I'm not sure if it includes the information you needed. If not, you may directly contact the authors of the paper.

**Comment by kexinhuang12345** [comment]
Great, thank you Mufei!
