### ISSUE TITLE
WeaveEdgeFeaturizer bug (number of edges)

### ISSUE THREAD

**Issue by nbrosse** [awslabs/dgl-lifesci#191]
WeaveEdgeFeaturizer does not work for some smiles 

https://github.com/awslabs/dgl-lifesci/blob/91ef785bb5659108ade5d71ca88e0e89de16963a/python/dgllife/utils/featurizers.py#L1881

```python
from dgllife.utils import WeaveAtomFeaturizer, WeaveEdgeFeaturizer, smiles_to_bigraph

edge_featurizer = WeaveEdgeFeaturizer()
atom_featurizer = WeaveAtomFeaturizer()

graph1 = smiles_to_bigraph("CO", edge_featurizer=edge_featurizer, node_featurizer=atom_featurizer, add_self_loop=True)
```
OK

```python
from dgllife.utils import WeaveAtomFeaturizer, WeaveEdgeFeaturizer, smiles_to_bigraph

edge_featurizer = WeaveEdgeFeaturizer()
atom_featurizer = WeaveAtomFeaturizer()

graph2 = smiles_to_bigraph("CCO", edge_featurizer=edge_featurizer, node_featurizer=atom_featurizer, add_self_loop=True)
```

Error `dgl._ffi.base.DGLError: Expect number of features to match number of edges. Got 9 and 7 instead.`

**Comment by mufeili** [comment]
`WeaveEdgeFeaturizer` does not work for bidirected molecular graphs. According to the doc, "This featurization is performed for a complete graph of atoms with self loops added".

**Comment by nbrosse** [comment]
Thank you, I am sorry I should have better read the documentation !

**Comment by mufeili** [comment]
No worries :)
