### ISSUE TITLE
Do not downgrade scikit-learn requirement

### ISSUE THREAD

**Issue by we-taper** [awslabs/dgl-lifesci#198]
It seems weird to downgrade `scikit-learn` because [python 3.6 is not supported](https://github.com/awslabs/dgl-lifesci/pull/179) . Could you relax this requirement?

Python 3.6 has been deprecated by [pytorch](https://github.com/pytorch/pytorch/issues/66462), and for people who are still on 3.6, the pip installer will be able to find an older version of `scikit-learn` to install.

https://github.com/awslabs/dgl-lifesci/blob/91ef785bb5659108ade5d71ca88e0e89de16963a/python/setup.py#L41

**Comment by mufeili** [comment]
Addressed in https://github.com/awslabs/dgl-lifesci/pull/197
