### ISSUE TITLE
sider dataset

### ISSUE THREAD

**Issue by ph-mehdi** [awslabs/dgl-lifesci#201]
[Here](https://github.com/awslabs/dgl-lifesci/blob/54649fba5c72adb0ccbcb58391b8c4d7a032fbb1/python/dgllife/data/sider.py#L21) you use the sider dataset based on 27 organ system classes. I can't figure out how this dataset is created because [there ](http://sideeffects.embl.de/)is nothing like this to download. I need the same dataset based on High-Level Terms in MedDRA.
Can you guide me?
Thanks

**Comment by mufeili** [comment]
Perhaps you can ask the [DeepChem](https://github.com/deepchem/deepchem) team. SIDER is part of the MoleculeNet created by the same group of people.

**Comment by ph-mehdi** [comment]
thank you
