### ISSUE TITLE
Example showing how to use an ML model to tune pretrained generative models? 

### ISSUE THREAD

**Issue by PatWalters** [awslabs/dgl-lifesci#219]
Is there an example showing how one can use an ML model to tune the output of the pre-trained generative models?

**Comment by mufeili** [comment]
What's your purpose of tuning a pre-trained generative model?

**Comment by PatWalters** [comment]
I want to fine-tune the pre-trained model to output molecules meeting a specific profile.   For instance, outputting molecules that score highly using a target-specific regression model.

**Comment by mufeili** [comment]
I see. DGL-LifeSci does not support that. You may want to check the original codebase of JTVAE or other generative models.

**Comment by PatWalters** [comment]
Thanks for your quick response.  I'm just curious about the use case for the pre-trained generative models.

**Comment by mufeili** [comment]
No problems! I'll close the issue for now. Feel free to reopen it if you have any further questions.
