### ISSUE TITLE
Question regarding molecular graphs with Hydrogen atoms

### ISSUE THREAD

**Issue by eereenah-fast** [awslabs/dgl-lifesci#37]
Hello! Thank you for sharing this library!

I have a question concerning graph generation from CSV. 

I want to create graphs with custom features, which can later be used with SchNet for property prediction task. I am using `MoleculeCSVDataset` class with custom node and edge featurizers partially taken from [`TencentAlchemyDataset` ](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/data/alchemy.py) (`alchemy_nodes` and `alchemy_edges`). How can I create graphs from custom CSV, so that the Hydrogen atoms are present as nodes, as that information is needed in SchNet? 

Many thanks in advance and apologies for the trivial question.

**Comment by mufeili** [comment]
Thank you for your question and I think it's a good one. For data pre-processing we proceed as follows:

**Comment by eereenah-fast** [comment]
Thanks a lot for your help!
