### ISSUE TITLE
Virtual node support for mol_to_graph

### ISSUE THREAD

**Issue by sooheon** [awslabs/dgl-lifesci#63]
I see this is on the roadmap in #18. I was looking to dig into this topic, and would prefer to build on top of an established project rather than reinvent the wheel. 

The default way I'd approach it is to port the logic from [here](https://github.com/ardigen/MAT/blob/1c7af06e440d967064763dc765847413b5770f05/src/featurization/data_utils.py#L102) such that BaseFeaturizer can take a boolean arg to add dummy node, which would replace the 0 index node with a fully connected dummy node with a unique feature vector.

We would need a way to derive the dummy vector. The way MAT does it is by prepending a 0th index to the onehot vector, incrementing the # of classes). We could have handle this in each featurizing function (i.e. atom_type_one_hot has a add_dummy kwarg), or handle it at the level of the ConcatFeaturizer.

**Comment by mufeili** [comment]
Hi Sooheon,

Thank you for your contact and I'm glad to add this feature to DGL-LifeSci. Personally I find it make better sense to use an additional node feature for indicating whether this is a dummy node and handle that at the level of converting a SMILES string/molecular graph into a DGLGraph, e.g. adding an `add_dummy_node` flag to 
 smiles_to_bigraph for both handling the graph structure and related features. I have some questions:

1. I think virtual nodes/dummy nodes are the same. Which name do you prefer?
2. I believe the dummy node should be connected to all atoms, which is not how the MAT code handled the adjacency matrix.
3. When a model requires edge features, how should we deal with the edges for the dummy node. Do we simply use one additional feature for the "dummy edges"?

**Comment by sooheon** [comment]
You're right this should go in the `smiles_to_*_graph` constructor, because it's changing the topology of the graph. 

1. We should allow N > 1 for virtual nodes, considering results from [Big Bird](https://arxiv.org/pdf/2007.14062.pdf). In this case virtual is slightly better than dummy which implies a single node class (imo).
2. I agree. Actually, MAT dummy node is interpreted slightly differently because they're using transformers. Even though the dummy node is disjoint in terms of the adjacency matrix, the adj matrix is only one part of the final attention weights. The transformer will compute self-attention over the dummy node even without any adjacencies. For gnns with explicit edges, yes the virtual node(s) should be explicitly connected to every other node.
3. I think using one additional boolean feature and appending it to others via `ConcatFeaturizer` is the way to go. Adding a virtual edge would then be `[1] + [0] * bond_feat_size` if all other featurizers had `encode_unknown=False`.

As for the actual featurizer, I see two options:

Option 1: actually add the virtual node(s) to the Rdkit Mol object with some agreed upon Atom and Bond types. Then the virtual_node_featurizer_func signature can be `atom -> [float]` like all other featurizer funcs.
 - Pro: keeps same signature, can be composed with ConcatFeaturizer
 - Con: preempts some atom and bond type for this use -- future featurizers need to be aware of this. For bond, we can use `rdkit.Chem.rdchem.BondType.OTHER`, or `UNSPECIFIED`, but for atoms it's uglier because AFAIK you have to give a valid atom type. 

Option 2: special case the virtual node featurization, so that it is added to the output of whatever Atom/Bond featurizers are given. 
 - Pro: don't need to mess with creating a Mol
 - Con: behavior is different from other featurizers

Any other ways you see to approach this?

**Comment by mufeili** [comment]
1. If I understand correctly, the Big Bird paper basically introduces multiple virtual nodes for each sequence such that these virtual nodes are connected to all real nodes and the virtual nodes are connected with each other themselves. We can turn `add_dummy_node` into a flag like `num_virtual_nodes` for specifying the number of virtual nodes to add. In this case, I'd prefer using IDs V, V+1, ..., V+N-1 for virtual nodes so that we can keep the original IDs of real nodes, where V is the number of real nodes and N is the number of virtual nodes.
2. I'd prefer performing featurization for virtual nodes with `smiles_to_*_graph`/`mol_to_*_graph` for the time being. The option 1 introduces the risk of modifying the RDKit molecule object and potential overhead for featurization functions. The option 2 sounds better to me. It seems that featurization for virtual nodes tends to be simple and this can be something handled directly in `smiles_to_*_graph`/`mol_to_*_graph`. Even if it turns out that there are more complex featurization for these virtual nodes, we can just add an additional arguments like `virtual_node_featurizer` and `virtual_edge_featurize` in `smiles_to_*_graph`/`mol_to_*_graph`.

**Comment by sooheon** [comment]
Ok. What should be done about data_field?

1. `num_virtual_nodes` only takes effect if there already is a featurizer passed in -- it inspects output ndata/edata and adds virtual nodes to existing data_field(s)
2. `mol_to_graph` takes 2 additional args, `atom_data_field` and `bond_data_field`. Requires user to ensure the fields match.

I prefer 1, but it's a tradeoff.

**Comment by mufeili** [comment]
> Ok. What should be done about data_field?
> 
> 1. `num_virtual_nodes` only takes effect if there already is a featurizer passed in -- it inspects output ndata/edata and adds virtual nodes to existing data_field(s)
> 2. `mol_to_graph` takes 2 additional args, `atom_data_field` and `bond_data_field`. Requires user to ensure the fields match.
> 
> I prefer 1, but it's a tradeoff.
> 
> edit: just realized that option 1 can also work when featurizer is not passed in, as you can then just update the topology and do nothing to the features.

Yes, option 1 sounds good to me. If you don't have further concerns, I think I can move on to do the coding. Alternatively, would you like to contribute that?

**Comment by sooheon** [comment]
If you can do so, that would be great, I'm still getting acquainted with the code and test suite.

**Comment by sooheon** [comment]
Since we're doing this post-featurization in `mol_to_graph`, it may also make sense to extend this to `add_self_loop`. BaseBondFeaturizer assumes non-self-loop graphs, but self loops can be added to resulting edata in the same way as virtual edges, as far as I can tell. Do you have any thoughts on this?

**Comment by mufeili** [comment]
> Since we're doing this post-featurization in `mol_to_graph`, it may also make sense to extend this to `add_self_loop`. BaseBondFeaturizer assumes non-self-loop graphs, but self loops can be added to resulting edata in the same way as virtual edges, as far as I can tell. Do you have any thoughts on this?

That's a good point. Do you know any models with both self loops and edge features? How do they handle them?

**Comment by sooheon** [comment]
I don't know of any offhand. Conceptually I think of it as transformer style encoding with relative position (==edge) embeddings determined by edge features.

I think in terms of featurization the simplest way is to add +1 to the `feature_size()` so the 0th index feature is a boolean for `is_self_loop`, when it is True, all other features are 0. If you add both self-loop and virtual nodes, you'd have `[is_virt, is_self, ...]` for your edge feature vector. 

I don't want to get too deep into abstractions, but the final thing we can consider is the possibility of also adding fully connected edges (== transformer) or arbitrarily random edges (== big bird).

**Comment by mufeili** [comment]
Sorry for the late reply. #74 supported virtual nodes and #73 handles edge features indicating self loops.

**Comment by sooheon** [comment]
Thank you for this, I will check this out.
