### ISSUE TITLE
Parallel _pre_process in MoleculeCSVDataset

### ISSUE THREAD

**Issue by sooheon** [awslabs/dgl-lifesci#64]
As SMILES counts get to 100k+, parallelization of graph construction and featurization becomes a necessity. 

The following is a helper I use for this locally:

```python
from joblib import Parallel, delayed, cpu_count


def pmap(pickleable_fn, data, n_jobs=cpu_count() - 1, verbose=1, **kwargs):
    """
    Parallel map using joblib.

    :param pickleable_fn: Fn to map over data.
    :param data: Data to be mapped over.
    :param kwargs: Additional args for f
    :return: Mapped output.
    """
    return Parallel(n_jobs=n_jobs, verbose=verbose)(
        delayed(pickleable_fn)(d, **kwargs) for d in data
    )


# usage
# pmap(smiles_to_graph, smiles_strings, node_featurizer=nf, edge_featurizer=ef) -> [graph]
```

This is pretty plug and play, but it will not work with the sequential log_every logger (but joblib has its own logger whose verbosity you can control), and requires another dependency. If you're okay with these downsides, I can go ahead and make a PR for this.

**Comment by sooheon** [comment]
Also, please lmk the steps for local testing :)

**Comment by mufeili** [comment]
That's a great idea. We can disable `log_every` if `n_jobs` is greater than 1. 

I'm ok to have new dependencies and I think `joblib` is a light package. One quick question is are there any differences between `joblib` and `multiprocessing`? I used `multiprocessing.pool` for parallel graph construction in the past.

For local testing, you need to install dgllife from source with your modifications and run a test script. You may define your test function [here](https://github.com/awslabs/dgl-lifesci/blob/master/tests/data/test_new_dataset.py).

**Comment by sooheon** [comment]
I just found the joblib api more attractive at first glance and haven't had problems with it. Have not used multiprocessing in anger.

**Comment by mufeili** [comment]
That's fine. We can go with joblib first.

**Comment by mufeili** [comment]
Supported by @sooheon in #67 .
