### ISSUE TITLE
Murcko scaffolds doesn't work for certain SMILES

### ISSUE THREAD

**Issue by skrsna** [awslabs/dgl-lifesci#84]
Hi, 

I noticed weird behavior with ScaffoldSplitter for certain datasets. Specifically, this [code](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/utils/splitters.py#L494). The output from `MurckoScaffold.MurckoScaffoldSmiles` is blank and all the SMILES/data points are added to test instead of splitting between train/val/test. This can be resolved by using `AllChem.MurckoDecompose` as suggested in official rdkit's [issue](https://github.com/rdkit/rdkit/issues/2845#issuecomment-565141397) tracker. I can open a PR with the solution if you'd like along with some checks to make sure train indices doesn't cross over to val/test and vice versa. 

Thanks!!

**Comment by mufeili** [comment]
Hi Krishna, 

Thank you for the report. How is `MurckoScaffoldSmiles` different from `MurckoDecompose`? If `MurckoDecompose` is the same as `MurckoScaffoldSmiles` in cases where `MurckoScaffoldSmiles` applies, then we can simply replace `MurckoScaffoldSmiles` with `MurckoDecompose`. If not, we may want to add an additional splitter function with `MurckoDecompose` and raise an error in `ScaffoldSplitter` when `MurckoScaffoldSmiles` fails.

**Comment by skrsna** [comment]
Hi Mufei Li, 

I'm not sure about what's the difference but as you can see here from official rdkit repo `MurckoScaffoldSmiles` gives an empty string for non-ring systems. I didn't find anything particular that explains the difference between `MurckoScafffoldSmiles` and `MurckoDecompose` other than it was superseded in the recent rdkit releases. I tested a problematic SMILES using both functions and the results are weird. 

```
                                                                                                             
In [1]: from rdkit import Chem                                                                                                                         

In [2]: from rdkit.Chem.Scaffolds import MurckoScaffold                                                                                                

In [3]: from rdkit.Chem import AllChem                                                                                                                 

In [4]: smiles = 'CC(F)C(F)=CF'                                                                                                                        

In [5]: MurckoScaffold.MurckoScaffoldSmiles(smiles)                                                                                                    
Out[5]: ''

In [6]: AllChem.MurckoDecompose(Chem.MolFromSmiles(smiles))                                                                                            
Out[6]: <rdkit.Chem.rdchem.Mol at 0x7fa2c6bb5ee0>

In [7]: Chem.MolToSmiles(AllChem.MurckoDecompose(Chem.MolFromSmiles(smiles)))                                                                          
Out[7]: ''

In [8]: import rdkit                                                                                                                                   

In [9]: rdkit.__version__                                                                                                                              
Out[9]: '2018.09.3'


```
My guess is that `MurckScaffoldSmiles` is working as it should and gives empty strings for non-ring systems where as `MurckoDecompose` gives an rdkit mol object which can be used to compare and sort the scaffolds and do the splitting. But if you convert the rdkit mol object back to smiles you get an empty string. I'd like you hear to your thoughts about this.

**Comment by mufeili** [comment]
I see. Just tried myself and it seems that `MurckoDecompose` is equivalent to `MurckScaffoldSmiles` with `includeChirality=True`. Could you open a PR to replace `MurckScaffoldSmiles` with `MurckoDecompose` and remove the `includeChirality` flag?

**Comment by skrsna** [comment]
Thanks! I just opened a PR #85. Let me know if you need more edits and fixes to the code. Cheers!
