### ISSUE TITLE
[JTVAE] Broken Training Script

### ISSUE THREAD

**Issue by mufeili** [awslabs/dgl-lifesci#93]
Currently, there is a bug in the training script.

**Comment by sparklytopaz** [comment]
I get IndexError while trying to train my own model.
Is there a problem in fetch.py which is called by _next_data() in class _SingleprocessDataLoaderIter() in dataloader.py?
I have indetigfied the error line to be - 
data = [self.dataset[idx] for idx in possibly_batched_index]

**Comment by mufeili** [comment]
> I get IndexError while trying to train my own model.
> Is there a problem in fetch.py which is called by _next_data() in class _SingleprocessDataLoaderIter() in dataloader.py?
> I have indetigfied the error line to be -
> data = [self.dataset[idx] for idx in possibly_batched_index]

How did you trigger that error?

**Comment by sparklytopaz** [comment]
In the directory dgl-lifesci/examples/reaction_prediction/rexgen_direct 
Command - 
python find_reaction_center_train.py --train-path /dgl-lifesci/examples/reaction_prediction/rexgen_direct/test2.txt --val-path /dgl-lifesci/examples/reaction_prediction/rexgen_direct/test2validate.txt
I have also attached the test2.txt and test2val.txt file
[test2.txt](https://github.com/awslabs/dgl-lifesci/files/5265855/test2.txt)
[test2validate.txt](https://github.com/awslabs/dgl-lifesci/files/5265905/test2validate.txt)
Error - 

![error_github](https://user-images.githubusercontent.com/31735343/93973302-9af42c00-fd91-11ea-9510-d2bae9f9936b.PNG)

**Comment by sparklytopaz** [comment]
Am i doing something wrong? The pretrained model is working great, Also is there an open source software that converts smiles to reaction smiles/smirks ?

**Comment by mufeili** [comment]
The issue mentioned by @sparklytopaz is moved to #95 .
