### ISSUE TITLE
JTNN example does not work

### ISSUE THREAD

**Issue by trinayan** [awslabs/dgl-lifesci#97]
Hi,

I am trying to run the JTNN example in dgl-lifesci/examples/generative_models/jtvae. When I run python train.py, I get this error

"(rdkit-env) root@nucar-nice:/home/trinayan/dgl-lifesci/examples/generative_models/jtvae# python3 train.py 
Using backend: pytorch
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(args)
  File "train.py", line 31, in main
    depth=args.depth)
  File "/root/anaconda3/envs/rdkit-env/lib/python3.6/site-packages/dgllife-0.2.5-py3.6.egg/dgllife/model/model_zoo/jtnn/jtnn_vae.py", line 53, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '<built-in function dir>/jtnn/vocab.txt'"

Not sure if i need to download anything since the github page says the datasets will be downloaded automatically for ZINC. 

Any help will be appreciated

Thanks

**Comment by trinayan** [comment]
Has anyone had a change to look into this? . Thanks

**Comment by mufeili** [comment]
Hi @trinayan, sorry for the inconvenience. I think the training part of the JTNN example is broken due to DGL 0.5 and I'm working on fixing it, which might take some time. If you are in an urgent need of using that, I would recommend you to directly use the [authors' code](https://github.com/wengong-jin/icml18-jtnn).

**Comment by yjw123456** [comment]
Dear Mufeili,
Sorry for interuption. I found the jtnn example still not work. 
FileNotFoundError: [Errno 2] No such file or directory: '<built-in function dir>/jtnn/vocab.txt'

Can you give me some advice?

Bests
