### ISSUE TITLE
TypeError: 'method' object is not subscriptable - (pretrained_model )

### ISSUE THREAD

**Issue by sparklytopaz** [awslabs/dgl-lifesci#98]
![image](https://user-images.githubusercontent.com/31735343/94449906-3c341580-01ca-11eb-82df-26b97803eda9.png)
In the pretrained model - reaction_prediction_pretrained.ipynb
Command -wget https://data.dgl.ai/dgllife/reaction_prediction_pretrained.ipynb
I am getting the above error.
python 3.8
The notebook is in proper directory.
In fact, i have run it previously and did not face this issue.
facing this issue after creating a new environment to train a model on my own dataset
please help

**Comment by mufeili** [comment]
Sorry for the inconvenience.

As of DGL 0.5, `batch_num_nodes` and `batch_num_edges` are now functions returning tensors rather than properties returning lists as in <DGL0.5. For example, you need to replace `.batch_num_edges[i]` by `.batch_num_edges()[i].item()`. I should have fixed these issues in the latest repo and you can do a git pull.

**Comment by sparklytopaz** [comment]
![image](https://user-images.githubusercontent.com/31735343/94510747-2576d880-0235-11eb-983b-2fef99dd7ff6.png)
I dont think the repo contains the pre-trained model -
I did a https://data.dgl.ai/dgllife/reaction_prediction_pretrained.ipynb

**Comment by mufeili** [comment]
> ![image](https://user-images.githubusercontent.com/31735343/94511136-19d7e180-0236-11eb-8095-d7cd1bf621a6.png)
> 
> .item() worked! This is another bug
> I dont think the repo contains the pre-trained model -
> I did a wget https://data.dgl.ai/dgllife/reaction_prediction_pretrained.ipynb
> Edit - new error
> ![image](https://user-images.githubusercontent.com/31735343/94511981-7cca7800-0238-11eb-9286-0dea4354a4fc.png)

Apology for that. The error is due to the change of `WLNRankDataset`, not the pre-trained models. I've updated the jupyter notebook host on S3. Can you try re-downloading it?

**Comment by sparklytopaz** [comment]
I tried redownloading the jupyter notebook and still facing the same issue? should i redownload dgllife?
