### ISSUE TITLE
DGLError: Expect number of features to match number of edges (MoleculeCSVDataset)

### ISSUE THREAD

**Issue by kienerj** [awslabs/dgl-lifesci#99]
I'm trying to load my molecules into DGL using the MoleculeCSVDataset class and then I get the mentioned error:

    DGLError: Expect number of features to match number of edges. Got 26 and 38 instead.

My code:

    dataset = MoleculeCSVDataset(df, partial(smiles_to_bigraph, add_self_loop=True), CanonicalAtomFeaturizer(), 
            CanonicalBondFeaturizer(), 'SMILES', 'dglgraph.bin', n_jobs=6)

df = pandas DataFrame with a SMILES column and multiple label columns (for multi-label classification)

When I set CanonicalBondFeaturizer() to None, this works fine. The molecules in the dataset are prepared so that there aren't any weird things in there that could explain the issue (all are valid RDKit molecules). 

How can I solve this problem?

**Comment by mufeili** [comment]
Can you try replacing `CanonicalBondFeaturizer()` with `CanonicalBondFeaturizer(self_loop=True)`?

**Comment by kienerj** [comment]
Wow thanks for the quick reply. amazing. and indeed this solves the issue.
